spring:
  datasource:
    url : jdbd:mysql://localhost/mydb?useSSL=false&serverTimzone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin
sever:
  port: 8080
jwt:
  secret: mySuperSecretKeyWhichShouldBeVeryLongAndRandom
  expiration: 3600000

